[build]
  command = "npm run build --prod"
  publish = "frontend/dist" # Répertoire de sortie de l'application Angular (après la compilation)

[[redirects]]
  from = "/api/*"
  to = "https://backend-ardw.onrender.com/api/:splat"
  status = 200
  force = true
